### ISSUE TITLE
Upgrading to 5.0.0-rc.9 causes Unexpected value 'CalendarModule' imported by the module 

### ISSUE THREAD

**Issue by seigneur** [lbertenasco/ap-ng2-fullcalendar#47]
## Issue
App was not having any issues, However on upgrading to Angular 5.0.0-rc.9, it causes following ### error:

1. `Uncaught Error: Unexpected value 'CalendarModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:466) [<root>]
    at :4200/vendor.bundle.js:185660:44 [<root>]
    at Array.forEach (<anonymous>) [<root>]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:15071) [<root>]
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules (compiler.js:33484) [<root>]
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:33445) [<root>]
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAsync (compiler.js:33361) [<root>]
    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:230) [<root>]
    at PlatformRef.webpackJsonp.../../../core/esm5/core.js.PlatformRef.bootstrapModule (core.js:5443) [<root>]
    at Object.../../../../../src/main.ts (main.ts:10) [<root>]
    at Object.0 (main.bundle.js:7543) [<root>]`

### warnings:

1. `WARNING in ./node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (//node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (node_modules/webpack/lib/Compilation.js:701:24)
    at Compilation.finish (node_modules/webpack/lib/Compilation.js:559:9)
    at applyPluginsParallel.err (node_modules/webpack/lib/Compiler.js:506:17)
    at node_modules/tapable/lib/Tapable.js:289:11
    at node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)`

2. `WARNING in ./node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (node_modules/webpack/lib/Compilation.js:701:24)
    at Compilation.finish (node_modules/webpack/lib/Compilation.js:559:9)
    at applyPluginsParallel.err (node_modules/webpack/lib/Compiler.js:506:17)
    at node_modules/tapable/lib/Tapable.js:289:11
    at node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)`

## Version
1. ap-angular2-fullcalendar: 1.3.2
2. fullcalendar: 3.6.2
3. Angular: 5.0.0-rc.9

## How To Replicate
1. Download the [demo app] (https://github.com/lbertenasco/ap-ng2-fullcalendar-demo)
2. Change the @angular dependencies to 5.0.0-rc.9
3. Run ng serve

The demo application is using 4.4.4 which is stable, but I am trying to keep the build upgraded for the date|pipe changes introduced in 5.0.0

**Comment by seigneur** [comment]
Closing this as it was fixed by removing the node_modules directory.
[See link](https://github.com/angular/angular/issues/15763#issuecomment-339343522)

**Comment by jloosli** [comment]
@seigneur I've removed the node_modules directory a couple of times and I'm still getting this error with Angular 5.0.0. Any suggestions?

**Comment by seigneur** [comment]
@jloosli just to check make sure you remove the node_modules inside 
<app>/node_modules/ap-ng2-fullcalendar/***node_modules***

Also, you will have to do it after every npm install. I will need to research further to see what the root cause is, but the above link should lead you to to some more options.

**Comment by jloosli** [comment]
Just for completeness...here's the latest result I get (without removing `node_modules` within your package). This might help with some of your troubleshooting.

> ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /projects/appointments/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol CalendarModule in /projects/appointments/node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.d.ts, resolving symbol CalendarModule in /projects/appointments/node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.d.ts

In following that link, I followed the instructions to change `src/tsconfig.app.json` by adding the following to "complierOptions":

```json
"paths": {
  "@angular/*": [
    "../node_modules/@angular/*"
  ]
}
```

That allows the app to compile without errors and without having to remove node_modules within `ap-angular2-fullcalendar`. However, when I run the app, I get the following warning in the console:

```
client:147 ./node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ap-angular2-fullcalendar/src/calendar/calendar.js
 @ ./node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
msgWarnings @ client:147
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
```

The app still runs, but it would be good to get those items taken care of. I'm not too familiar with developing NPM packages, but is there are reason why you've got node_modules inside your package instead of using @angular packages within the root `node_modules`?

**Comment by lbertenasco** [comment]
Hi @jloosli !
The package itself doesn't have a node_modules folder. It gets automatically created on install.
The issue here is that the @angular version for `ap-ng2-fullcalendar` is fixed to 4.x.x and since you are using 5.x.x it seems it's creating an issue. I'll check it out this weekend and release a fix :)

**Comment by aljazerzen** [comment]
Any updates? Is Angular version updated to 5.x.x?

**Comment by lbertenasco** [comment]
Hi @aljazerzen, yes the newest `1.3.7` version has support for Angular 5.x.x.
