### ISSUE TITLE
Angular5 !! Warning

### ISSUE THREAD

**Issue by alan345** [lbertenasco/ap-ng2-fullcalendar#50]
Hello! Thanks for this package !

I have this warning after updating to angular 5:

```
WARNING in ./node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/alan/app/arte/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/alan/app/arte/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/Users/alan/app/arte/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/Users/alan/app/arte/node_modules/webpack/lib/Compiler.js:506:17)
    at /Users/alan/app/arte/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/alan/app/arte/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/alan/app/arte/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.js
 @ ./node_modules/ap-angular2-fullcalendar/index.js
 @ ./src/app/userCalendar/userCalendar.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/alan/app/arte/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/alan/app/arte/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/Users/alan/app/arte/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/Users/alan/app/arte/node_modules/webpack/lib/Compiler.js:506:17)
    at /Users/alan/app/arte/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/alan/app/arte/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/alan/app/arte/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ap-angular2-fullcalendar/angular2-fullcalendar.js
 @ ./node_modules/ap-angular2-fullcalendar/index.js
 @ ./src/app/userCalendar/userCalendar.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

Thanks!!

**Comment by lbertenasco** [comment]
Hi @alan345 !
Please upgrade to `ap-angular2-fullcalendar@1.3.3` and check if the issue is fixed.
