### ISSUE TITLE
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator'

### ISSUE THREAD

**Issue by king2088** [lbertenasco/ap-ng2-fullcalendar#78]
use ap-ng2-fullcalendar in ionic3
```
package.json
"dependencies": {
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/compiler-cli": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "ap-angular2-fullcalendar": "^1.3.1",
    ............
},
"devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@ionic/cli-plugin-cordova": "1.6.1",
    "@ionic/cli-plugin-ionic-angular": "1.4.1",
    "ionic": "3.18.0",
    "typescript": "2.3.4"
  }
```

the error infomation:
```
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in /Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in /Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/ap-angular2-fullcalendar/node_modules/@angular/core/core.d.ts
    at syntaxError (/Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at simplifyInContext (/Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:23870:23)
    at StaticReflector.simplify (/Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:23882:13)
    at StaticReflector.annotations (/Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:23331:41)
    at NgModuleResolver.resolve (/Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:13883:70)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:14473:60)
    at addNgModule (/Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:23050:58)
    at /Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:23061:14
    at Array.forEach (<anonymous>)
    at _createNgModules (/Users/ubeing/works/Posify/posify-pos-fb-united/node_modules/@angular/compiler/bundles/compiler.umd.js:23060:26)
```

**Comment by lbertenasco** [comment]
Please check: https://github.com/lbertenasco/ap-ng2-fullcalendar/issues/57
